# Default values for postgresql-envoy-tls-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dnsName: "" # 👀
databaseEndpoint: "" # 👀
certificate:
  issuerName: "" # 👀
  issuerKind: "ClusterIssuer"

service:
  hostname: "" # 👀
  type: LoadBalancer
  port: 5432

replicaCount: 1

image:
  repository: envoyproxy/envoy-contrib
  pullPolicy: IfNotPresent
  # !!! 👉 Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 1001

securityContext:
  runAsUser: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
