apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-envoy-tls-proxy.fullname" . }}-pgbouncer-auth
stringData:
  POSTGRESQL_USERNAME: {{ .Values.database.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRESQL_DATABASE: {{ .Values.database.database | quote }}
  POSTGRESQL_HOST: {{ .Values.database.host | quote }}
  POSTGRESQL_PORT: {{ .Values.database.port | quote }}
  PGBOUNCER_AUTH_USER: {{ .Values.database.username | quote }}
  PGBOUNCER_DATABASE: {{ .Values.database.database | quote }}
  PGBOUNCER_IGNORE_STARTUP_PARAMETERS: "ssl_renegotiation_limit"
