apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-envoy-tls-proxy.fullname" . }}-pgbouncer-auth
stringData:
  # See https://github.com/bitnami/bitnami-docker-pgbouncer/blob/master/1/debian-11/rootfs/opt/bitnami/scripts/pgbouncer-env.sh#L83
  POSTGRESQL_USERNAME: {{ .Values.database.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRESQL_DATABASE: {{ .Values.database.database | quote }}
  POSTGRESQL_HOST: {{ .Values.database.host | quote }}
  POSTGRESQL_PORT: {{ .Values.database.port | quote }}
  PGBOUNCER_AUTH_USER: {{ .Values.database.username | quote }}
  PGBOUNCER_DATABASE: {{ .Values.database.database | quote }}
  PGBOUNCER_IGNORE_STARTUP_PARAMETERS: "ssl_renegotiation_limit"
  {{ if .Values.pgbouncer.extraEnv }}
  {{- toYaml .Values.pgbouncer.extraEnv | nindent 2 }}
  {{- end }}
