apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-envoy-tls-proxy.fullname" . }}
  labels:
    {{- include "postgresql-envoy-tls-proxy.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgresql-envoy-tls-proxy.selectorLabels" . | nindent 4 }}
