apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgresql-envoy-tls-proxy.serviceAccountName" . }}
  labels:
    {{- include "postgresql-envoy-tls-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
